server:
  port: 8080
  max-http-header-size: 102400
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///test?serverTimezone=UTC
    username: root
    password: rootroot